version: '3'
services:
  counter:
    image: cannizzaromic/appcounternginx
    links:
      - redis
    deploy:
      restart_policy:
        condition: always
  frontend:
    image: cannizzaromic/frontcounternginx
    ports:
      - "7070:80"
    links:
      - counter
    deploy:
      restart_policy:
        condition: always
  redis:
    image: redis:5-alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: always