apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-kubernetes-pods
    spec:
      containers:
      - name: minikube-second
        image: minikube-second:v1
        ports:
          - containerPort: 8080
        imagePullPolicy: Never
